name: CI - Node.js & TypeScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar lint
        run: npm run lint

      - name: Verificar formatação
        run: npm run format:check

      - name: Compilar projeto
        run: npm run build

      - name: Rodar testes com cobertura
        run: npm run test:coverage

  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: build-and-test 
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          echo | docker build -f Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest .

      - name: Push da imagem pro Docker Hub
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest